# SITE CONFIGURATION

title: Four Frames by Andrew Weymouth
description: A collection of four-frame film analyses by Andrew Weymouth
repository: ""  # Add a URL or keep it empty as needed
baseurl: "/four-frames/"
url: "https://aweymo.github.io/"

google_tag_manager: ""  # Add your GTM ID or keep it empty as needed

# THEME SETTINGS

navigation:  # Navigation links
  - {name: 'Home', link: 'https://aweymo.github.io/base'}
  - {name: 'CV', link: 'https://aweymo.github.io/base/cv'}
  - {name: 'Animation', link: 'https://aweymo.github.io/base/animation'}
  - {name: 'Art and Design', link: 'https://aweymo.github.io/base/art'}
  - {name: 'Audio Docs', link: 'https://aweymo.github.io/base/audio'}
  - {name: 'Field Recording', link: 'https://aweymo.github.io/base/field'}
  - {name: 'Four Frames', link: 'https://aweymo.github.io/four-frames'}
  - {name: 'Music', link: 'https://aweymo.github.io/base/music'}
  - {name: 'Subscribe and Contact', link: 'https://aweymo.github.io/base/contact'}

email: andrewrainsweymouth@gmail.com
github_username: aweymo

plugins: []

collections:
  films:
    output: true
